version: '3.8'

services:
  postgres-database:
    image: postgres
    container_name: 'postgres-api-prisma-tabacaria-ts'
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: rootes
    networks:
      - backend

  pgadmin:
    image: dpage/pgadmin4
    container_name: 'pgadmin-api-prisma-tabacaria'
    ports:
      - "8080:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    networks:
      - backend

networks:
  backend:
